global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'moonplants_ml_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000'] # Points to local ML API running on port 8000, modify if hosted remotely

