-- ============================================================
-- MoonPlants — Initial Schema Migration
-- ============================================================
-- Created:  2026-03-02
-- Source:   database/schema.sql + database/migration_iot_v2.sql
--
-- This file represents the full current state of the database.
-- It is the baseline for all future migrations managed via
-- `supabase migration new` + `supabase db push`.
--
-- ⚠️  Do NOT edit this file after it has been pushed to Cloud.
--     Create a new migration instead:
--       npm run db:new <migration_name>
-- ============================================================

-- ============================================================
-- EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE device_status   AS ENUM ('unclaimed', 'claimed', 'revoked');
CREATE TYPE command_type    AS ENUM ('PUMP_WATER', 'LIGHT_ON', 'LIGHT_OFF', 'SET_CONFIG');
CREATE TYPE command_status  AS ENUM ('queued', 'sent', 'acked', 'failed', 'expired', 'canceled');
CREATE TYPE image_source    AS ENUM ('user', 'perenual', 'none');
CREATE TYPE watering_source AS ENUM ('manual', 'auto', 'command');

-- ============================================================
-- SHARED TRIGGER FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- TABLE: devices
-- Physical ESP32 controllers
-- ============================================================

CREATE TABLE devices (
    id                          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id               UUID        REFERENCES auth.users(id) ON DELETE SET NULL,

    status                      device_status NOT NULL DEFAULT 'unclaimed',
    display_name                TEXT,

    -- Capabilities
    channels_count              INT         NOT NULL DEFAULT 4 CHECK (channels_count >= 1 AND channels_count <= 16),
    supports_pumps              BOOLEAN     NOT NULL DEFAULT TRUE,
    supports_light              BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Firmware
    firmware_version            TEXT,

    -- Claim security
    claim_code_hash             TEXT        NOT NULL,
    claim_code_used_at          TIMESTAMPTZ,
    failed_claim_attempts       INT         NOT NULL DEFAULT 0,
    last_failed_claim_at        TIMESTAMPTZ,

    -- Anti-replay
    last_seq                    BIGINT      NOT NULL DEFAULT 0,

    -- Telemetry
    last_seen_at                TIMESTAMPTZ,

    -- Timestamps
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_devices_owner  ON devices(owner_user_id) WHERE owner_user_id IS NOT NULL;
CREATE INDEX idx_devices_status ON devices(status);

CREATE TRIGGER update_devices_updated_at
    BEFORE UPDATE ON devices
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE  devices           IS 'Physical IoT controllers (ESP32)';
COMMENT ON COLUMN devices.last_seq  IS 'Monotonic request counter for anti-replay';

-- ============================================================
-- TABLE: device_credentials
-- HMAC secrets for IoT authentication
-- ============================================================

CREATE TABLE device_credentials (
    device_id       UUID    PRIMARY KEY REFERENCES devices(id) ON DELETE CASCADE,
    hmac_secret     BYTEA   NOT NULL,
    secret_version  INT     NOT NULL DEFAULT 1,
    rotated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  device_credentials            IS 'HMAC secrets for IoT device authentication';
COMMENT ON COLUMN device_credentials.hmac_secret IS 'Readable only by backend via service role';

-- ============================================================
-- TABLE: species_cache
-- Cache of Perenual API data
-- ============================================================

CREATE TABLE species_cache (
    id              UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    perenual_id     INT     UNIQUE NOT NULL,

    common_name     TEXT,
    scientific_name JSONB,  -- ["Ficus lyrata"]
    family          TEXT,
    type            TEXT,
    watering        TEXT,
    sunlight        JSONB,  -- ["full sun", "part shade"]
    indoor          BOOLEAN,
    cycle           TEXT,

    default_image_url TEXT, -- stored in Supabase Storage

    raw_json        JSONB,  -- full Perenual response for future use

    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_species_cache_perenual_id ON species_cache(perenual_id);

CREATE TRIGGER update_species_cache_updated_at
    BEFORE UPDATE ON species_cache
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE species_cache IS 'Plant species cache from Perenual API';

-- ============================================================
-- TABLE: plants
-- User plants linked to a device channel
-- ============================================================

CREATE TABLE plants (
    id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Device binding
    device_id               UUID        REFERENCES devices(id) ON DELETE SET NULL,
    soil_channel            INT         CHECK (soil_channel >= 1 AND soil_channel <= 16),

    -- Names
    name                    TEXT,
    species_name            TEXT        NOT NULL,
    species_cache_id        UUID        REFERENCES species_cache(id) ON DELETE SET NULL,

    -- Media
    image_url               TEXT,
    image_source            image_source NOT NULL DEFAULT 'none',

    -- Parameters
    age_months              INT         CHECK (age_months >= 0),
    pot_volume_ml           INT         CHECK (pot_volume_ml > 0),
    pot_height_cm           NUMERIC(5,2) CHECK (pot_height_cm > 0),
    pot_diameter_cm         NUMERIC(5,2) CHECK (pot_diameter_cm > 0),

    -- Automation
    auto_watering_enabled   BOOLEAN     NOT NULL DEFAULT FALSE,
    auto_light_enabled      BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Care
    last_watered_at         TIMESTAMPTZ,

    -- Timestamps
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One channel = one plant per device
CREATE UNIQUE INDEX idx_plants_device_channel
    ON plants(device_id, soil_channel)
    WHERE device_id IS NOT NULL AND soil_channel IS NOT NULL;

CREATE INDEX idx_plants_owner         ON plants(owner_user_id);
CREATE INDEX idx_plants_device        ON plants(device_id)         WHERE device_id IS NOT NULL;
CREATE INDEX idx_plants_species_cache ON plants(species_cache_id)  WHERE species_cache_id IS NOT NULL;

CREATE TRIGGER update_plants_updated_at
    BEFORE UPDATE ON plants
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE  plants              IS 'User plants linked to IoT sensor channel';
COMMENT ON COLUMN plants.soil_channel IS 'Soil sensor channel number on controller (1..N)';

-- ============================================================
-- TABLE: measurements
-- Sensor readings — always linked to a plant
-- ============================================================

CREATE TABLE measurements (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    plant_id            UUID        NOT NULL REFERENCES plants(id)  ON DELETE CASCADE,
    device_id           UUID        NOT NULL REFERENCES devices(id) ON DELETE CASCADE,

    -- Readings
    soil_moisture_raw   INT,
    soil_moisture_pct   NUMERIC(5,2) CHECK (soil_moisture_pct >= 0 AND soil_moisture_pct <= 100),
    air_temp_c          NUMERIC(5,2) CHECK (air_temp_c >= -50 AND air_temp_c <= 100),
    air_humidity_pct    NUMERIC(5,2) CHECK (air_humidity_pct >= 0 AND air_humidity_pct <= 100),
    light_lux           NUMERIC(8,2) CHECK (light_lux >= 0),

    -- Telemetry
    battery_v           NUMERIC(4,2),
    rssi_dbm            INT,

    -- Anti-replay / idempotency
    seq                 BIGINT      NOT NULL,

    -- Timestamps
    measured_at         TIMESTAMPTZ NOT NULL,
    ingested_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_measurements_plant_time  ON measurements(plant_id,  measured_at DESC);
CREATE INDEX idx_measurements_device_time ON measurements(device_id, measured_at DESC);

CREATE UNIQUE INDEX idx_measurements_idempotency ON measurements(device_id, seq, plant_id);

COMMENT ON TABLE  measurements     IS 'IoT sensor readings linked to a plant';
COMMENT ON COLUMN measurements.seq IS 'Monotonic device counter (anti-replay + idempotency)';

-- ============================================================
-- TABLE: watering_events
-- Watering facts (manual + auto + command)
-- ============================================================

CREATE TABLE watering_events (
    id          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    plant_id    UUID            NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
    source      watering_source NOT NULL DEFAULT 'manual',
    water_ml    INT             CHECK (water_ml > 0),
    happened_at TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    note        TEXT,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_watering_events_plant ON watering_events(plant_id, happened_at DESC);

COMMENT ON TABLE watering_events IS 'Watering facts for history and analysis';

-- ============================================================
-- TABLE: predictions
-- Watering predictions (rule-based / ML)
-- ============================================================

CREATE TABLE predictions (
    id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    plant_id                UUID        NOT NULL REFERENCES plants(id) ON DELETE CASCADE,

    predicted_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    next_watering_at        TIMESTAMPTZ,
    recommended_water_ml    INT         CHECK (recommended_water_ml > 0),
    confidence              NUMERIC(3,2) CHECK (confidence >= 0 AND confidence <= 1),

    model                   TEXT        NOT NULL DEFAULT 'rulebased_v1',
    details                 JSONB,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_predictions_plant ON predictions(plant_id, predicted_at DESC);

COMMENT ON TABLE predictions IS 'Next watering predictions';

-- ============================================================
-- TABLE: device_commands
-- Command queue for IoT devices
-- ============================================================

CREATE TABLE device_commands (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id       UUID            NOT NULL REFERENCES devices(id) ON DELETE CASCADE,

    type            command_type    NOT NULL,
    payload         JSONB           NOT NULL DEFAULT '{}',
    -- payload examples:
    --   PUMP_WATER: { "channel": 2, "water_ml": 120, "max_duration_sec": 20 }
    --   LIGHT_ON:   { "duration_sec": 3600 }
    --   SET_CONFIG: { "measurement_interval_sec": 300 }

    status          command_status  NOT NULL DEFAULT 'queued',

    -- Scheduling
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    send_after      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW() + INTERVAL '1 hour',

    -- Lifecycle
    sent_at         TIMESTAMPTZ,
    acked_at        TIMESTAMPTZ,

    -- Idempotency
    idempotency_key TEXT            UNIQUE NOT NULL,

    -- Device result
    result          JSONB
);

CREATE INDEX idx_device_commands_device_status
    ON device_commands(device_id, status)
    WHERE status IN ('queued', 'sent');

CREATE INDEX idx_device_commands_expires
    ON device_commands(expires_at)
    WHERE status IN ('queued', 'sent');

COMMENT ON TABLE  device_commands               IS 'Command queue for IoT devices with ACK flow';
COMMENT ON COLUMN device_commands.idempotency_key IS 'Prevents duplicate commands';

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE devices             ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_credentials  ENABLE ROW LEVEL SECURITY;
ALTER TABLE species_cache       ENABLE ROW LEVEL SECURITY;
ALTER TABLE plants              ENABLE ROW LEVEL SECURITY;
ALTER TABLE measurements        ENABLE ROW LEVEL SECURITY;
ALTER TABLE watering_events     ENABLE ROW LEVEL SECURITY;
ALTER TABLE predictions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_commands     ENABLE ROW LEVEL SECURITY;

-- === devices ===
CREATE POLICY "Users can view their claimed devices"
    ON devices FOR SELECT USING (owner_user_id = auth.uid());

-- Claim is done via server endpoint (service role)

-- === device_credentials ===
-- No policies → blocked for anon/authenticated; service role only

-- === species_cache ===
CREATE POLICY "Anyone can read species cache"
    ON species_cache FOR SELECT USING (true);

-- === plants ===
CREATE POLICY "Users can view their own plants"
    ON plants FOR SELECT USING (owner_user_id = auth.uid());

CREATE POLICY "Users can insert their own plants"
    ON plants FOR INSERT WITH CHECK (owner_user_id = auth.uid());

CREATE POLICY "Users can update their own plants"
    ON plants FOR UPDATE USING (owner_user_id = auth.uid());

CREATE POLICY "Users can delete their own plants"
    ON plants FOR DELETE USING (owner_user_id = auth.uid());

-- === measurements ===
CREATE POLICY "Users can view measurements of their plants"
    ON measurements FOR SELECT
    USING (plant_id IN (SELECT id FROM plants WHERE owner_user_id = auth.uid()));
-- INSERT: service role only (IoT ingestion)

-- === watering_events ===
CREATE POLICY "Users can view watering events of their plants"
    ON watering_events FOR SELECT
    USING (plant_id IN (SELECT id FROM plants WHERE owner_user_id = auth.uid()));

CREATE POLICY "Users can insert watering events for their plants"
    ON watering_events FOR INSERT
    WITH CHECK (plant_id IN (SELECT id FROM plants WHERE owner_user_id = auth.uid()));

-- === predictions ===
CREATE POLICY "Users can view predictions for their plants"
    ON predictions FOR SELECT
    USING (plant_id IN (SELECT id FROM plants WHERE owner_user_id = auth.uid()));
-- INSERT: service role only (prediction engine)

-- === device_commands ===
CREATE POLICY "Users can view commands for their devices"
    ON device_commands FOR SELECT
    USING (device_id IN (SELECT id FROM devices WHERE owner_user_id = auth.uid()));

CREATE POLICY "Users can insert commands for their devices"
    ON device_commands FOR INSERT
    WITH CHECK (device_id IN (SELECT id FROM devices WHERE owner_user_id = auth.uid()));

-- ============================================================
-- VIEWS
-- ============================================================

CREATE OR REPLACE VIEW plants_with_latest_measurements AS
SELECT
    p.*,
    m.soil_moisture_pct  AS last_soil_moisture,
    m.air_temp_c         AS last_air_temp,
    m.air_humidity_pct   AS last_air_humidity,
    m.light_lux          AS last_light,
    m.measured_at        AS last_measurement_at
FROM plants p
LEFT JOIN LATERAL (
    SELECT * FROM measurements
    WHERE plant_id = p.id
    ORDER BY measured_at DESC
    LIMIT 1
) m ON true;

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Get latest measurement for a plant
CREATE OR REPLACE FUNCTION get_latest_measurement(p_plant_id UUID)
RETURNS TABLE (
    soil_moisture_pct   NUMERIC,
    air_temp_c          NUMERIC,
    air_humidity_pct    NUMERIC,
    light_lux           NUMERIC,
    measured_at         TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT m.soil_moisture_pct, m.air_temp_c, m.air_humidity_pct, m.light_lux, m.measured_at
    FROM measurements m
    WHERE m.plant_id = p_plant_id
    ORDER BY m.measured_at DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- Average measurements over N days
CREATE OR REPLACE FUNCTION get_average_measurements(
    p_plant_id  UUID,
    p_days      INTEGER DEFAULT 7
)
RETURNS TABLE (
    avg_soil_moisture   NUMERIC,
    avg_air_temp        NUMERIC,
    avg_air_humidity    NUMERIC,
    avg_light           NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        AVG(m.soil_moisture_pct)::NUMERIC(5,2),
        AVG(m.air_temp_c)::NUMERIC(5,2),
        AVG(m.air_humidity_pct)::NUMERIC(5,2),
        AVG(m.light_lux)::NUMERIC(8,2)
    FROM measurements m
    WHERE m.plant_id = p_plant_id
      AND m.measured_at >= NOW() - (p_days || ' days')::INTERVAL;
END;
$$ LANGUAGE plpgsql;

-- Expire stale commands (run via pg_cron every 5 min)
CREATE OR REPLACE FUNCTION expire_stale_commands()
RETURNS void AS $$
BEGIN
    UPDATE device_commands
    SET status = 'expired'
    WHERE status IN ('queued', 'sent')
      AND expires_at < NOW();
END;
$$ LANGUAGE plpgsql;

-- pg_cron setup (uncomment after enabling the extension in Supabase dashboard):
-- SELECT cron.schedule('expire-commands', '*/5 * * * *', 'SELECT expire_stale_commands()');

